### ISSUE TITLE
濁点の最初ポイント

### ISSUE THREAD

**Issue by aaronbell** [nagamaki008/kapakana#1]
濁点に最初ポイントはLightとRegularに違います。
<img width="708" alt="kapakana_glyphs_-_kapakana" src="https://user-images.githubusercontent.com/8460297/97130270-2d278100-16fe-11eb-8138-62997d626c5e.png">

Lightに上の方にあります。Regularに右側にあります。そしたら、interpolationはおかしくなります。

**Comment by aaronbell** [comment]
上のモードは”Show Master Compatibility"で見えます。control-option-command-n.

**Comment by nagamaki008** [comment]
解決しました。ありがとうございます

**Comment by aaronbell** [comment]
Looks fixed :)
