### ISSUE TITLE
Font metrics following CJK or Latin?

### ISSUE THREAD

**Issue by aaronbell** [nagamaki008/kapakana#10]
The Google CJK recommendations for CJK fonts are different than for standard Latin fonts, so as a CJK font, Kapakana should follow those guidelines. However, as the Hiragana / Katakana fall more in line with standard Latin metrics than a CJK font, I think it would make more sense to follow Latin font metrics. Attached are mock-ups of the fonts as they currently stand with Latin metrics. 

[Archive.zip](https://github.com/nagamaki008/kapakana/files/5718317/Archive.zip)

**Comment by davelab6** [comment]
Since this is a kana only font, that sounds good to me.

**Comment by nagamaki008** [comment]
I think this font is unlikely to be used in combination with other Japanese font.

**Comment by aaronbell** [comment]
Thanks. Sounds good.
