### ISSUE TITLE
Interpolation problems in `Kapakana[wght].ttf`

### ISSUE THREAD

**Issue by behdad** [nagamaki008/kapakana#12]
Hello!

This is an automatically-generated report about possible interpolation problems in `Kapakana[wght].ttf`, as found in the Google Fonts catalog.

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/d856d89bb54c39f9fcc99a44ea000e0a37367cc3/reports/Kapakana%5Bwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/d856d89bb54c39f9fcc99a44ea000e0a37367cc3/reports/Kapakana%5Bwght%5D.ttf.pdf).

The report follows:
```
Glyph Ecircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Icircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Itilde was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Jcircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Ntilde was not compatible:
  Masters: '', 'wght=300.0':
    Contour 2 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Ocircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Otilde was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph Ucircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph ecircumflex was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
Glyph ntilde was not compatible:
  Masters: '', 'wght=300.0':
    Contour 1 start point differs: 0 in '', 34 in 'wght=300.0'; reversed: False
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please accept our apologies and ignore / close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by nagamaki008** [comment]
Thank you for your comment.
I will check the font data and fix the data if necessary.

**Comment by nagamaki008** [comment]
Fixed the glyph that was requested.
Best regards.

**Comment by behdad** [comment]
Thank you.
