### ISSUE TITLE
モノスペース？

### ISSUE THREAD

**Issue by aaronbell** [nagamaki008/kapakana#2]
LightとRegularは同じ広さを欲しいですか？ある字は同じ（例えば u-hira、e-hira), けど他の字にはRegularはもっと広いです。どちらの方を使いつもりですか？

u-hira Light: 697 funits
u-hira Regular: 697 funits

ka-hira Light: 767 funits
ka-hira Regular: 794 funits

**Comment by aaronbell** [comment]
It appears that the following glyphs are still varying widths:
ismall-hira
vu-hira
za-kata
ho-kata
yusmall-kata

**Comment by nagamaki008** [comment]
修正しました。
