### ISSUE TITLE
Font metrics

### ISSUE THREAD

**Issue by aaronbell** [nagamaki008/kapakana#4]
I would like to suggest that, for this project, we do not align with the standard CJK recommendations of 880 / -120 and 1160 / 288. 

Kapakana is a copperplate script-style design with proportional kana included. Due to the scriptual nature of the design, it has rather extensive flourishes in both Latin and Japanese that are at risk of clipping in a situation where we enforce the normal winAscent and winDescent values.

<img width="579" alt="97131020-49c4b880-1700-11eb-89c0-1701cc0909be" src="https://user-images.githubusercontent.com/8460297/99455395-a0c34500-28dc-11eb-8298-e870c8740a3e.png">

A full list:

under /IJ
under /J
under /Jcircumflex
under /Thorn
under /f
under /g
under /ij
under /j
under /dotlessj
under /jcircumflex
under /p
under /thorn
under /q
under /y
under /yacute
under /ydieresis
under /z
under /ff
under /fi
under /esmall-hira
under /na-hira
under /yasmall-hira
under /yusmall-hira
under /yosmall-hira
under /ra-hira
under /usmall-kata
under /esmall-kata
under /ta-kata
under /da-kata
under /ne-kata
under /mi-kata
under /yasmall-kata
under /yusmall-kata
under /wasmall-kata
under /wi-kata
under /vi-kata
under /mu

In order to fit these glyphs within the standard CJK metrics, we will need to scale the font down by 30%, resulting in really small letters on the body in both Latin and Japanese. Instead, I believe we should treat this font akin to a standard Latin only design. Additionally, because the Japanese Kana align with the heights of the Latin (baseline to cap height), there should not be any adverse affects on Japanese text.

**Comment by nagamaki008** [comment]
フォントサイズを30％縮小しました。
ラテン文字もあわせて小さくしています。
