### ISSUE TITLE
Weight variation should be applied to all glyphs

### ISSUE THREAD

**Issue by aaronbell** [nagamaki008/kapakana#8]
Right now just the Japanese glyphs have the weight variation applied. Please also do the same with the Latin and other glyphs.

**Comment by nagamaki008** [comment]
かな文字以外は既存フォントの流用のため、バリアブル用にリメイクしてから作業をする必要があります。かなり時間がかかるのでご了承ください。
Since existing fonts are used except for kana characters, it is necessary to remake them for variable use before starting work. Please note that it will take a considerable amount of time

**Comment by nagamaki008** [comment]
ラテン文字のウェイトを作成しました。

**Comment by aaronbell** [comment]
It appears that this bug has been closed, but I am not seeing an update to the repository. Is there a reason?

**Comment by nagamaki008** [comment]
更新されていませんでした、すみません。
データアップロードしました

It wasn't updated, I'm sorry.
Data uploaded
